apiVersion: skaffold/v1beta2
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: quarkus-simplerest
      context: .
      docker:
        dockerfile: src/main/docker/Dockerfile.dev
      sync:
        '**/*.java': .
  
deploy:
  kubectl:
    manifests:
      - k8s/quarkus-simplerest-deployment.yaml
      - k8s/quarkus-simplerest-ip-service.yaml
